spring:
    datasource:
        url: jdbc:mysql:// #エンドポイント/databese名
        username: #user名
        password: #パスワード
        driver-class-name: com.mysql.cj.jdbc.Driver
        
cloud:
  aws:
    stack:
      # CloudFormationのstack名を自動収集しない
      auto: false
    region:
      # EC2のmetadataを自動収集しない
      auto: false
      static: ap-northeast-1