package com.nbapp.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;

import com.nbapp.domain.Test01;

@Mapper
public interface Test01Mapper {

	List<Test01> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test01
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test01
     *
     * @mbg.generated
     */
    int insert(Test01 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test01
     *
     * @mbg.generated
     */
    int insertSelective(Test01 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test01
     *
     * @mbg.generated
     */
    Test01 selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test01
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Test01 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test01
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Test01 record);
}